name: update-every-10m-F1-FriSun
on:
  schedule:
    - cron: '*/10 * * * 5,6,0'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call F1 API route fetching new documents
        run: |
          curl --request GET \
          --url '${{ secrets.CRON_JOB_UPDATE_F1_ENDPOINT }}' \
          --header 'Authorization: Bearer ${{ secrets.CRON_JOB_SECRET }}'
