name: update-every-6h-MonThu
on:
  schedule:
    - cron: '0 */2 * * 1-4'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call F1 API route fetching new documents
        run: |
          curl --request GET \
          --url '${{ secrets.CRON_JOB_UPDATE_F1_ENDPOINT }}' \
          --header 'Authorization: Bearer ${{ secrets.CRON_JOB_SECRET }}'
      - name: Call F2 API route fetching new documents
        run: |
          curl --request GET \
          --url '${{ secrets.CRON_JOB_UPDATE_F2_ENDPOINT }}' \
          --header 'Authorization: Bearer ${{ secrets.CRON_JOB_SECRET }}'
      - name: Call F3 API route fetching new documents
        run: |
          curl --request GET \
          --url '${{ secrets.CRON_JOB_UPDATE_F3_ENDPOINT }}' \
          --header 'Authorization: Bearer ${{ secrets.CRON_JOB_SECRET }}'
